"""Regenerate the API reference and static re-exports from registered workflows."""

from collections import defaultdict
import inspect
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import pybms as pb  # noqa: E402
from pybms._registry import REGISTRY  # noqa: E402


def generate():
    if len(REGISTRY) != 100:
        raise RuntimeError(f"Expected 100 public workflows, found {len(REGISTRY)}")
    groups = defaultdict(list)
    for name, info in REGISTRY.items():
        groups[info["category"]].append(name)
    lines = [
        "# The 100-function reference",
        "",
        "Generated by `python tools/generate_docs.py`. Import once with `import pybms as pb`.",
        "Use `pb.function_help('name')` for the same signature, explanation and example in Python.",
        "",
        "Table examples use `df = pb.classification_data(rows=100, features=4)` unless a specific schema is shown.",
        "Names such as `price`, `city`, `date`, `id` refer to columns in your own dataset.",
        "`X`/`y` are numeric features/targets, `result` is a TrainingResult, and `network` is a native Model.",
        "",
        "Established numerical methods come from NumPy, pandas, scikit-learn and Matplotlib.",
        "Pybms supplies the convenience API, validation, orchestration and native dense training implementation.",
        "",
        "| Category | Functions |",
        "|---|---:|",
    ]
    for category, names in groups.items():
        lines.append(f"| {category} | {len(names)} |")
    for category, names in groups.items():
        lines.extend(["", f"## {category}", ""])
        for name in names:
            info = pb.function_help(name)
            module = REGISTRY[name]["function"].__module__.split(".")[-1]
            lines.extend(
                [
                    f"### `{name}`",
                    "",
                    "```python",
                    info["signature"],
                    "```",
                    "",
                    info["description"],
                    "",
                    "```python",
                    info["example"],
                    "```",
                    "",
                    f"Source: [`pybms/{module}.py`](../pybms/{module}.py).",
                    "",
                ]
            )
    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    (docs / "API_REFERENCE.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    modules = defaultdict(list)
    for name, info in REGISTRY.items():
        modules[info["function"].__module__].append(name)
    stub = ["# Generated static re-exports for IDE completion."]
    for module, names in modules.items():
        stub.append(f"from .{module.split('.')[-1]} import (")
        stub.extend(f"    {name} as {name}," for name in names)
        stub.append(")")
    stub.extend(
        [
            "from .model import Model as Model, Sequential as Sequential, History as History, easy as easy",
            "from .layers import Dense as Dense",
            "from .optimizers import SGD as SGD, Adam as Adam",
            "from .device import device as device",
            "from .data import DataSplit as DataSplit",
            "from .training import TrainingResult as TrainingResult",
            "from .optimization import OptimizeResult as OptimizeResult",
            "from .syntax import SyntaxResult as SyntaxResult",
        ]
    )
    exceptions = [
        name
        for name in pb.__all__
        if inspect.isclass(getattr(pb, name)) and issubclass(getattr(pb, name), pb.PyBMSError)
    ]
    stub.append("from .exceptions import (")
    stub.extend(f"    {name} as {name}," for name in exceptions)
    stub.extend(
        [")", "", "__version__: str", "__all__: list[str]", "", "def about() -> dict: ...", ""]
    )
    (ROOT / "pybms" / "__init__.pyi").write_text("\n".join(stub), encoding="utf-8")
    print(f"Generated reference and IDE exports for {len(REGISTRY)} functions.")


if __name__ == "__main__":
    generate()
